version: '3.8'

services:
  # Бэкенд на FastAPI
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Чтобы база данных SQLite сохранялась на сервере
    restart: always

  # Фронтенд на Next.js
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://your-server-ip:8000
    restart: always