version: '3.8'

services:
  backend:
    build: ./backend
    container_name: news-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/news.db:/app/news.db # Пробрасываем файл базы
    restart: always

  frontend:
    build: ./frontend
    container_name: news-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always